name: Martin Stamat Photography
favicon: null
layout_spectrum: 0.6250765938311815
typography_spectrum: 0.27006114018149674
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.1743491559755057
  lightness: 0.5493386469315737
  saturation: 0.49789145472459495
  rhythmicContrast: 0.9100182368420064
purpose: []
